# Header
menu:
  Home: /
  Archives: /archives
  Github:
    url: https://github.com/emodo
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Menu


blogImage: http://7xnjo6.com1.z0.glb.clouddn.com/20151015-IMG_9096.jpg
# URL of the Home page image
index_cover: http://7xnjo6.com1.z0.glb.clouddn.com/20151015-IMG_1069-3.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-25097607-5

# Addthis ID
addthis:

# Social Accounts
twitter_url: https://twitter.com/dushichen
twitter_handle:
facebook_url:
github_url: https://github.com/emodo
gitlab_url:
linkedin_url:
mailto:
